### ISSUE TITLE
https://linkedsoftwaredependencies.org/engines/node/v8.1.3 wrong links

### ISSUE THREAD

**Issue by bjdmeest** [LinkedSoftwareDependencies/npm-extraction-server#3]
Stuff like `"https://linkedsoftwaredependencies.orgengines/node"` should be `"https://linkedsoftwaredependencies.org/engines/node"` I guess

**Comment by joachimvh** [comment]
How do you even find things that fast, I forgot a slash in the startup command ... 2 minutes ago. :D 
Thx for finding it.
